### ISSUE TITLE
"Shall not act..."

### ISSUE THREAD

**Issue by mnot** [sftcd/policies-consultation#3]
> Covered Individuals shall not engage in any outside business, professional conduct, or other activities that are directly adverse to the interests of the IAB.

That seems ... problematic, depending on who is judging "directly adverse", and whether someone's employers' actions are considered in-scope.

**Comment by sftcd** [comment]
yeah, I'd say deleting that bit would be right

**Comment by sftcd** [comment]
Removed that bullet.
