### ISSUE TITLE
Board review

### ISSUE THREAD

**Issue by mnot** [sftcd/policies-consultation#4]
> Pending the Board’s review and resolution of a potential conflict of interest, disclosing Covered Individuals will conduct themselves so as to minimize the possible impact of the potential conflict of interest on the IAB.

Is this just a missed incidence of LLC board, or are we assuming that the LLC will review IAB conflicts, or...?

**Comment by mnot** [comment]
Happens in quite a few other places too.

**Comment by sftcd** [comment]
when doing the edits, I assumed board works for the B in IAB

**Comment by sftcd** [comment]
I'll close this for now as B==Board in IAB. We can s/Board/IAB/g later if that's better.
